# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nostr < Formula
  desc "A command-line client for the Nostr protocol"
  homepage "https://github.com/xdamman/nostr-cli"
  version "1.7.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xdamman/nostr-cli/releases/download/v1.7.12/nostr_darwin_amd64.tar.gz"
      sha256 "aa27b84f9ccb1c486070002f162d5740c2b2e97703850c50f71407b61d160d5b"

      define_method(:install) do
        bin.install "nostr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xdamman/nostr-cli/releases/download/v1.7.12/nostr_darwin_arm64.tar.gz"
      sha256 "57680f62be05d2d980d8325354fda99583551515057edc58f16c600e6c066112"

      define_method(:install) do
        bin.install "nostr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdamman/nostr-cli/releases/download/v1.7.12/nostr_linux_amd64.tar.gz"
      sha256 "11a07342545360f7d5e33fba7e2d4e727839e914d326538c53f851a7a081455f"
      define_method(:install) do
        bin.install "nostr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xdamman/nostr-cli/releases/download/v1.7.12/nostr_linux_arm64.tar.gz"
      sha256 "056f28f7a1e0209e66fe4745d073cb6041c8b183412e825f1209431c27515bb1"
      define_method(:install) do
        bin.install "nostr"
      end
    end
  end
end
